server:
  port: ${SERVER_PORT}

spring:
  application:
    name: user-manager-api
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          order_inserts: true
          order_updates: true
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
